// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkM6tep8RaE5jQuNuAuVP_uJITGB-eKOU',
    appId: '1:400998067848:web:6ad17813a16095347f393d',
    messagingSenderId: '400998067848',
    projectId: 'football-stats-648f7',
    authDomain: 'football-stats-648f7.firebaseapp.com',
    storageBucket: 'football-stats-648f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgvM1TgyYKg6pTSkfs8AW5dAVpqEV-0nc',
    appId: '1:400998067848:android:0ea55657c21ceef47f393d',
    messagingSenderId: '400998067848',
    projectId: 'football-stats-648f7',
    storageBucket: 'football-stats-648f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4gyfjFHJOtv_2xjSXdblDA-B1kQg5O-Q',
    appId: '1:400998067848:ios:1890aad8b6ce363c7f393d',
    messagingSenderId: '400998067848',
    projectId: 'football-stats-648f7',
    storageBucket: 'football-stats-648f7.appspot.com',
    iosClientId: '400998067848-67i5ucf5l16e5h96edgvn63necfpc1c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.footballStats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4gyfjFHJOtv_2xjSXdblDA-B1kQg5O-Q',
    appId: '1:400998067848:ios:c41e6cfa3416ee577f393d',
    messagingSenderId: '400998067848',
    projectId: 'football-stats-648f7',
    storageBucket: 'football-stats-648f7.appspot.com',
    iosClientId: '400998067848-afpl9ai9f9q5t01i128rlv78jnccplnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.footballStats.RunnerTests',
  );
}
